(() => {
  "use strict";

  const moduleHref = "organization-module.html";

  const catalog = [
    {
      id: "branch",
      title: "Branch Management",
      href: moduleHref,
      category: "Operations",
      componentRole: "Runs locations, local teams, stock movement, and branch performance.",
      description: "Locations, branch teams, local operations.",
      features: ["Branch records", "Local teams", "Operational scope"],
      sharedResources: ["Users", "Inventory", "Reports"],
    },
    {
      id: "departments",
      title: "Department Management",
      href: moduleHref,
      category: "Organization",
      componentRole: "Owns department structure, approvals, and internal workflow routing.",
      description: "Department users, workflows, and approvals.",
      features: ["Department roles", "Approvals", "Workflows"],
      sharedResources: ["Users", "Permissions", "Activity"],
    },
    {
      id: "hr",
      title: "HR Module",
      href: moduleHref,
      category: "People",
      componentRole: "Manages workforce records while sharing accounts with every module.",
      description: "Staff records, HR reports, and workforce structure.",
      features: ["Shared users", "Workforce reports", "Role access"],
      sharedResources: ["Users", "Permissions", "Reports"],
    },
    {
      id: "finance",
      title: "Finance Module",
      href: moduleHref,
      category: "Finance",
      componentRole: "Tracks financial activity and exposes summaries to reports and analytics.",
      description: "Finance summaries, payments, and reports.",
      features: ["Shared transactions", "Expense views", "Reports"],
      sharedResources: ["Transactions", "Reports", "Analytics"],
    },
    {
      id: "pharmacy",
      title: "Pharmacy Module",
      href: moduleHref,
      category: "Inventory",
      componentRole: "Handles pharmacy stock as its own workflow with shared inventory context.",
      description: "Pharmacy inventory and controlled operations.",
      features: ["Medicine stock", "Supplier control", "Shared inventory"],
      sharedResources: ["Inventory", "Suppliers", "Reports"],
    },
    {
      id: "inventory",
      title: "Inventory Module",
      href: moduleHref,
      category: "Inventory",
      componentRole: "Controls stock, transfers, availability, and warehouse records.",
      description: "Stock, items, transfers, and availability.",
      features: ["Stock levels", "Transfers", "Availability"],
      sharedResources: ["Branches", "Reports", "Analytics"],
    },
    {
      id: "logistics",
      title: "Logistics Module",
      href: moduleHref,
      category: "Operations",
      componentRole: "Coordinates delivery, dispatch, fleet, and tracking workflows.",
      description: "Dispatch, delivery, fleet, and tracking workflows.",
      features: ["Dispatch", "Tracking", "Delivery status"],
      sharedResources: ["Orders", "Branches", "Activity"],
    },
    {
      id: "sales",
      title: "Sales Module",
      href: moduleHref,
      category: "Revenue",
      componentRole: "Owns customers, sales activity, and order performance.",
      description: "Sales operations, customers, and performance.",
      features: ["Customers", "Sales activity", "Performance"],
      sharedResources: ["Customers", "Finance", "Analytics"],
    },
    {
      id: "analytics",
      title: "Analytics Module",
      href: moduleHref,
      category: "Insights",
      componentRole: "Reads shared module data and turns it into trends, charts, and insights.",
      description: "Realtime analytics, reports, and insights.",
      features: ["Charts", "Insights", "Activity trends"],
      sharedResources: ["Reports", "Activity", "All modules"],
    },
    {
      id: "admin",
      title: "Admin Module",
      href: "organization-admin.html",
      category: "Control",
      componentRole: "Controls organization settings, users, permissions, and module installation.",
      description: "Organization settings, users, roles, and modules.",
      features: ["Users", "Settings", "Permissions"],
      sharedResources: ["Users", "Permissions", "Modules"],
    },
    {
      id: "staff",
      title: "Staff Module",
      href: moduleHref,
      category: "People",
      componentRole: "Provides role-specific staff tasks and daily work views.",
      description: "Role-specific staff workspace.",
      features: ["Tasks", "Notifications", "Role access"],
      sharedResources: ["Users", "Notifications", "Activity"],
    },
    {
      id: "customer",
      title: "Customer Module",
      href: moduleHref,
      category: "Service",
      componentRole: "Manages customer records, support work, and service interactions.",
      description: "Customer operations and service workflows.",
      features: ["Customers", "Service records", "Support"],
      sharedResources: ["Sales", "Reports", "Activity"],
    },
    {
      id: "reporting",
      title: "Reporting Module",
      href: moduleHref,
      category: "Insights",
      componentRole: "Combines operational, finance, and organization data into exportable reports.",
      description: "Operational, finance, and organization reports.",
      features: ["Operational reports", "Financial summaries", "Exports"],
      sharedResources: ["Finance", "Operations", "Analytics"],
    },
  ];

  const workflows = {
    branch: { title: "Branch Operations", labels: ["Branch", "Manager", "Performance", "Status"], sample: ["Nairobi CBD", "Branch Lead", "92%", "Active"] },
    departments: { title: "Department Workflows", labels: ["Department", "Lead", "Workflow", "Approval"], sample: ["Operations", "Supervisor", "Procurement", "Pending"] },
    hr: { title: "HR Records", labels: ["Employee", "Role", "Attendance", "Payroll"], sample: ["Jane Staff", "Pharmacist", "Present", "Processed"] },
    finance: { title: "Finance Ledger", labels: ["Transaction", "Type", "Amount", "Status"], sample: ["Daily Sales", "Income", "45000", "Posted"] },
    pharmacy: { title: "Pharmacy Stock", labels: ["Medicine", "Supplier", "Expiry", "Stock"], sample: ["Amoxicillin", "Prime Supplier", "2027-04", "260"] },
    inventory: { title: "Inventory Control", labels: ["Item", "Warehouse", "Movement", "Quantity"], sample: ["Barcode Scanner", "Main Store", "Received", "12"] },
    logistics: { title: "Logistics Flow", labels: ["Shipment", "Driver/Fleet", "Route", "Status"], sample: ["ORD-2048", "Fleet 03", "Nairobi-Kisumu", "In transit"] },
    sales: { title: "Sales Pipeline", labels: ["Customer", "Order", "Value", "Status"], sample: ["Acme Retail", "SO-1021", "12800", "Confirmed"] },
    analytics: { title: "Analytics Insights", labels: ["Metric", "Source", "Trend", "Action"], sample: ["Revenue", "Finance", "+14%", "Review"] },
    admin: { title: "Admin Controls", labels: ["Setting", "Scope", "Owner", "Status"], sample: ["Role Policy", "Organization", "Admin", "Active"] },
    staff: { title: "Staff Tasks", labels: ["Task", "Assigned To", "Priority", "Status"], sample: ["Stock count", "Store Staff", "High", "Open"] },
    customer: { title: "Customer Operations", labels: ["Customer", "Interaction", "Ticket", "Status"], sample: ["Walk-in Client", "Support", "TCK-88", "Open"] },
    reporting: { title: "Reporting Center", labels: ["Report", "Scope", "Format", "Status"], sample: ["Monthly Summary", "Organization", "PDF", "Ready"] },
  };

  const byId = Object.fromEntries(catalog.map((module) => [module.id, module]));

  window.EnterpriseModules = Object.freeze({
    catalog,
    workflows,
    validIds: new Set(catalog.map((module) => module.id)),
    get: (id) => byId[String(id || "").trim().toLowerCase()] || null,
    permissionsFor: (id) => [`${id}.read`, `${id}.manage`, "organization.shared.read"],
  });
})();
